name: Mobile Build

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar Dependências
        run: yarn install --frozen-lockfile

      - name: Validar Build Expo
        run: npx expo prebuild --no-install --platform android
